### ISSUE TITLE
The standard way

### ISSUE THREAD

**Issue by wDraw** [BitcoinUnlimited/BUIP#2]
Why don't these BUIPs follow the standard way the BIPs work? I see no explanation on the way they work in this repository.

**Comment by gandrewstone** [comment]
BUIPs are not BIPs.  Please read https://www.bitcoinunlimited.info/articles for details on how BUIPs work.  But note that the content is much more free-form than BIPs -- your BUIP won't be summarily rejected because it lacks some chapter.  On the other hand, it may of course be voted NO if it is not sufficiently detailed...

**Comment by gandrewstone** [comment]
actually, maybe we should put a summary of how it works in this repo

**Comment by sickpig** [comment]
if you won't bit to it I'm going to add it to the README.md

**Comment by sickpig** [comment]
README updated, see https://github.com/BitcoinUnlimited/BUIP/commit/4157a30eb057467a2383977fe4548048d1509062
